# Generated by Django 3.1.1 on 2020-09-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200924_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='statur',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled Order', 'Canceled Order'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
