# Generated by Django 3.1.1 on 2020-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200924_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descriprion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
