# Generated by Django 3.1.1 on 2021-04-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201003_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_content',
            field=models.DecimalField(decimal_places=0, max_digits=10000, null=True),
        ),
    ]
